{% set data = load_file_regex(load_file='SConstruct', regex_pattern="env\\['cantera_version'\\] = .([\d.abrc]+).") %}

package:
    name: cantera
    version: {{ data.group(1) }}
source:
    git_url: https://github.com/Cantera/cantera.git
    git_tag: master
build:
    number: 0
    entry_points:
      - ck2cti = cantera.ck2cti:script_entry_point
      - ctml_writer = cantera.ctml_writer:main
requirements:
    build:
      - python {{ python }}
      - numpy {{ numpy }}
      - mkl  # [not win]
      - {{ compiler('c') }}
      - scons >=3.0
      - cython >=0.19
      - libboost
      - 3to2   # [py2k]
      - pywin32  # [win]
    run:
      - python {{ python }}
      - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
      - {{ pin_compatible('mkl') }}  # [not win]
      - vs2015_runtime  # [win]
test:
    imports:
      - cantera
    commands:
      - python -m unittest -v cantera.test
      - ck2cti --help
about:
    home: http://www.cantera.org
    summary: "Chemical kinetics, thermodynamics, and transport tool suite"
    license: BSD-3-Clause
    license_family: BSD
    license_file: License.txt
    dev_url: https://github.com/cantera/cantera
