{% set data = load_file_regex(load_file='SConstruct', regex_pattern="env\\['cantera_version'\\] = .([\d.abrc]+).") %}

package:
  name: cantera
  version: {{ data.group(1) }}

source:
  git_url: https://github.com/Cantera/cantera.git
  git_tag: master

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libboost
    - scons >=3.0
    - mkl  # [linux]
    - numpy

build:
  number: 0

outputs:
  - name: libcantera
    script: build_lib.sh  # [not win]
    script: build_lib.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - libboost
        - scons >=3.0
        - mkl  # [linux]
      run:
        - mkl  # [linux]
  - name: cantera
    script: build_py.sh  # [not win]
    script: build_py.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - libboost
        - scons >=3.0
        - mkl  # [linux]
        - python
        - numpy
        - cython
        - 3to2  # [py2k]
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - mkl  # [linux]
        - vs2015_runtime  # [win]
    build:
      entry_points:
        - ck2cti = cantera.ck2cti:script_entry_point
        - ctml_writer = cantera.ctml_writer:main
    test:
      imports:
        - cantera
      commands:
        - python -m unittest -v cantera.test
        - ck2cti --help

about:
  home: http://www.cantera.org
  summary: "Chemical kinetics, thermodynamics, and transport tool suite"
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  dev_url: https://github.com/cantera/cantera
